theme = "paper"
title = "废话练习"
Author = "Mark"
# disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # use disqus comments


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  # twitter = 'YOUR_TWITTER_ID'               # twitter.com/YOUR_TWITTER_ID
  # github = 'YOUR_GITHUB_ID'                 # github.com/YOUR_GITHUB_ID
  instagram = 'iandzsc'           # instagram.com/YOUR_INSTAGRAM_ID
  # linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://raw.githubusercontent.com/MarkRushB/bullshitPractice/main/frog.jpg'                 # gravatar email or image url
  name = 'bullshitPractice'
  bio = '“ 记录一些废话 ”'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  # graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  math = true                               # enable KaTex math typesetting globally

[params.giscus]
  data-repo="MarkRushB/bullshitPractice"
  data-repo-id="R_kgDOJvk5vw"
  data-category="Announcements"
  data-category-id="DIC_kwDOJvk5v84CX2WM"
  data-mapping="pathname"
  data-strict="0"
  data-reactions-enabled="1"
  data-emit-metadata="1"
  data-input-position="top"
  data-theme="noborder_dark"
  data-lang="zh-CN"
  data-loading="lazy"
  crossorigin="anonymous"
