theme = "paper"
title = "看见"
Author = "Mark"


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  instagram = 'iandzsc'           # instagram.com/YOUR_INSTAGRAM_ID


  # home page profile
  # avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'What is in your eyes？'
  bio = '照片收集活动'


  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTex math typesetting globally
